export const SET_GET_POKEMONS = "SET_GET_POKEMONS";
export const SUCCESS_GET_POKEMON = "SUCCESS_GET_POKEMON";
export const ERROR_GET_POKEMONS = "ERROR_GET_POKEMONS";
export const SET_OPEN_MODAL = "SET_OPEN_MODAL";
export const ADD_POKEMON = "ADD_POKEMON";
